apply plugin: 'com.android.application'

android {
    compileSdk 34
    namespace 'com.newsapp'
    defaultConfig {
        applicationId "com.newsapp"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "1.1"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    signingConfigs {
        release {
            storeFile file("../../release-key.jks")
            storePassword "newsapp123"
            keyAlias "newsapp"
            keyPassword "newsapp123"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    bundle {
        language {
            enableSplit = false
        }
    }
}
